[package]
name = "lrm_rust"
version = "0.1.0"
edition = "2024"
exclude = ["tools/**"]

# [patch.crates-io]
# # redirect burn to a merged fix (specific issue: cosine scheduler record serialized to linear)
# burn = { git = "https://github.com/tracel-ai/burn", rev = "5f9bcb7c512972bb3616c7031e86886db5a416fb" }

[dependencies]
# burn = { version = "0.21.0-pre.2", features = [
burn = { version = "0.20.1", features = [
    "train",
    "wgpu",
    "ndarray",
    "autodiff",
] }

log = "0.4"
image = "0.25.8" # for image processing
ndarray = "0.17.2"
num-traits = "0.2.19"
opencv = "0.98.2" # for CV tasks
rand = "0.9.2"
clap = { version = "4.5.48", features = ["derive"] } # for terminal arg parsing
reqwest = { version = "0.13.1", features = [
    "blocking",
] } # for HTTP requests to download data
serde = { version = "1.0.228", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
zip = "7.2.0"
flate2 = "1.1.2"
serde_json = "1.0.145"
tar = "0.4.44"
indicatif = "0.18.3"
bytemuck = "1.25"
crossbeam-channel = "0.5"
rustc-hash = "2.1"

[dev-dependencies]
plotters = { version = "0.3.7", default-features = false, features = ["svg_backend"] }

[target.'cfg(target_os = "macos")'.dependencies]
embed_plist = "1.2"

# onnxruntime = "0.0.14"
# hashmap = "0.0.0"
# show-image = "0.14.1"
# tract-onnx = "0.21.13"
